### ISSUE TITLE
DiffBind for ChIP-seq?

### ISSUE THREAD

**Issue by j-andrews7** [Barski-lab/biowardrobe#11]
I saw this mentioned at the AAI conference a few days ago and wanted to check it out and just had a question. Why use MAnorm rather than something that allows group comparisons like DiffBind (which is built on DEseq2) for the ChIP-seq analysis?

The program looks promising, but I think I will still have to use other tools for quantified ChIP-seq comparisons between groups.

I'm not sure if this project is still active, but figured I'd ask.

**Comment by tyomach** [comment]
Hi, 
We are actually investigating other tools to replace MAnorm. The chief advantage of MAnorm is that it expressly adjust for different signal to noise ratio. Diffbind does not do it. So far we are leaning towards THOR, but I will appreciate suggestions!
The project is still active and we have now switched most of the analysis to use Common Workflow Language.

**Comment by j-andrews7** [comment]
THOR is better than MAnorm, but it still can't account for batch effects or other confounding factors like DiffBind can. I have some pretty huge concerns with how they did their comparisons to other methods in their paper. It also doesn't take background input signal or regions that should be blacklisted into account. 

All in all, it probably doesn't matter that much what you choose, so long as it can compare groups of samples rather than single ones at a time. Glad to hear the project is still active.

**Comment by portah** [comment]
DiffBind is available at https://github.com/datirium/workflows/workflows/diffbind.cwl &  https://scidap.com/public/workflows/aLSZgiQo86Yk9AZeo
